language: generic
sudo: required



jobs:
  include:
    - os: linux
      dist: bionic
      node_js:
        - 12.10
    - os: osx
      osx_image: xcode12
      node_js:
        - 12.10

script: ./scripts/ci_build.sh



